CREATE TABLE PRODUIT (
    REFERENCE NUMBER PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    QUANTITE NUMBER NOT NULL,
    PRIX NUMBER(10,2) NOT NULL,
    CATEGORY VARCHAR2(100),
    FOURNISSEURS VARCHAR2(100),
    DATE_FAB DATE,
    DATE_EXP DATE,
    ID_FOURNISSEURS NUMBER,
    ID_CLIENTS NUMBER,
    -- Foreign Keys respecting the relations
    CONSTRAINT FK_PRODUIT_FOURNISSEUR FOREIGN KEY (ID_FOURNISSEURS) 
        REFERENCES FOURNISSEUR(ID_FOURNISSEUR) ON DELETE SET NULL,
    CONSTRAINT FK_PRODUIT_CLIENT FOREIGN KEY (ID_CLIENTS) 
        REFERENCES CLIENT(CIN) ON DELETE SET NULL
);

-- Insérer quelques données de test
-- NOTE: Make sure FOURNISSEUR and CLIENT tables are created and populated first!
INSERT INTO PRODUIT (REFERENCE, NOM, QUANTITE, PRIX, CATEGORY, FOURNISSEURS, DATE_FAB, DATE_EXP, ID_FOURNISSEURS, ID_CLIENTS)
VALUES (1001, 'Ordinateur Portable HP', 50, 2500.00, 'Informatique', 'Fournisseur Tech', TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2026-01-15', 'YYYY-MM-DD'), 3, 12345678);

INSERT INTO PRODUIT (REFERENCE, NOM, QUANTITE, PRIX, CATEGORY, FOURNISSEURS, DATE_FAB, DATE_EXP, ID_FOURNISSEURS, ID_CLIENTS)
VALUES (1002, 'Chaise de Bureau', 100, 350.50, 'Mobilier', 'Fournisseur XYZ', TO_DATE('2024-02-10', 'YYYY-MM-DD'), TO_DATE('2029-02-10', 'YYYY-MM-DD'), 2, 87654321);

INSERT INTO PRODUIT (REFERENCE, NOM, QUANTITE, PRIX, CATEGORY, FOURNISSEURS, DATE_FAB, DATE_EXP, ID_FOURNISSEURS, ID_CLIENTS)
VALUES (1003, 'Souris Sans Fil', 200, 45.00, 'Électronique', 'Fournisseur ABC', TO_DATE('2024-03-05', 'YYYY-MM-DD'), TO_DATE('2025-03-05', 'YYYY-MM-DD'), 1, 11223344);

COMMIT;

-- Vérifier l'insertion
SELECT * FROM PRODUIT;

